export const countries = [
  { name: "Afghanistan", code: "+93", id: "AF", format: "+93 xx xxx xxxx" },
  { name: "Albania", code: "+355", id: "AL", format: "+355 xx xxx xxxx" },
  { name: "Algeria", code: "+213", id: "DZ", format: "+213 xx xxx xxxx" },
  { name: "Andorra", code: "+376", id: "AD", format: "+376 xxx xxx" },
  { name: "Angola", code: "+244", id: "AO", format: "+244 xxx xxx xxx" },
  {
    name: "Antigua and Barbuda",
    code: "+1-268",
    id: "AG",
    format: "+1 (268) xxx-xxxx",
  },
  { name: "Argentina", code: "+54", id: "AR", format: "+54 9 xx xxxx-xxxx" },
  { name: "Armenia", code: "+374", id: "AM", format: "+374 xx xxxxxx" },
  { name: "Australia", code: "+61", id: "AU", format: "+61 x xxxx xxxx" },
  { name: "Austria", code: "+43", id: "AT", format: "+43 x xxxx xxxx" },
  { name: "Azerbaijan", code: "+994", id: "AZ", format: "+994 xx xxx xx xx" },
  { name: "Bahamas", code: "+1-242", id: "BS", format: "+1 (242) xxx-xxxx" },
  { name: "Bahrain", code: "+973", id: "BH", format: "+973 xxxx xxxx" },
  { name: "Bangladesh", code: "+880", id: "BD", format: "+880 x xxxx-xxxx" },
  { name: "Barbados", code: "+1-246", id: "BB", format: "+1 (246) xxx-xxxx" },
  { name: "Belarus", code: "+375", id: "BY", format: "+375 xx xxx-xx-xx" },
  { name: "Belgium", code: "+32", id: "BE", format: "+32 xxx xx xx xx" },
  { name: "Belize", code: "+501", id: "BZ", format: "+501 xxx-xxxx" },
  { name: "Benin", code: "+229", id: "BJ", format: "+229 xx xx xxxx" },
  { name: "Bhutan", code: "+975", id: "BT", format: "+975 x xxx xxxx" },
  { name: "Bolivia", code: "+591", id: "BO", format: "+591 x xxx xxxx" },
  {
    name: "Bosnia and Herzegovina",
    code: "+387",
    id: "BA",
    format: "+387 xx-xxxx-xxx",
  },
  { name: "Botswana", code: "+267", id: "BW", format: "+267 xx xxx xxx" },
  { name: "Brazil", code: "+55", id: "BR", format: "+55 xx xxxxx-xxxx" },
  { name: "Brunei", code: "+673", id: "BN", format: "+673 xxx xxxx" },
  { name: "Bulgaria", code: "+359", id: "BG", format: "+359 xxx xxx xxx" },
  { name: "Burkina Faso", code: "+226", id: "BF", format: "+226 xx xx xxxx" },
  { name: "Burundi", code: "+257", id: "BI", format: "+257 xx xx xxxx" },
  { name: "Cambodia", code: "+855", id: "KH", format: "+855 xx xxx xxx" },
  { name: "Cameroon", code: "+237", id: "CM", format: "+237 xxxx xxxx" },
  { name: "Canada", code: "+1", id: "CA", format: "+1 (xxx) xxx-xxxx" },
  { name: "Cape Verde", code: "+238", id: "CV", format: "+238 xxx xxxx" },
  {
    name: "Central African Republic",
    code: "+236",
    id: "CF",
    format: "+236 xx xx xxxx",
  },
  { name: "Chad", code: "+235", id: "TD", format: "+235 xx xx xx xx" },
  { name: "Chile", code: "+56", id: "CL", format: "+56 x xxxx xxxx" },
  { name: "China", code: "+86", id: "CN", format: "+86 xxx xxxx xxxx" },
  { name: "Colombia", code: "+57", id: "CO", format: "+57 xxx xxxxxxx" },
  { name: "Comoros", code: "+269", id: "KM", format: "+269 xxx xxxx" },
  { name: "Congo", code: "+242", id: "CG", format: "+242 xx xxx xxxx" },
  { name: "Costa Rica", code: "+506", id: "CR", format: "+506 xxxx xxxx" },
  { name: "Croatia", code: "+385", id: "HR", format: "+385 xx xxx xxxx" },
  { name: "Cuba", code: "+53", id: "CU", format: "+53 x xxxx xxxx" },
  { name: "Cyprus", code: "+357", id: "CY", format: "+357 xx xxxxxx" },
  {
    name: "Czech Republic",
    code: "+420",
    id: "CZ",
    format: "+420 xxx xxx xxx",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "+243",
    id: "CD",
    format: "+243 xx xxx xxxx",
  },
  { name: "Denmark", code: "+45", id: "DK", format: "+45 xx xx xx xx" },
  { name: "Djibouti", code: "+253", id: "DJ", format: "+253 xx xx xx xx" },
  { name: "Dominica", code: "+1-767", id: "DM", format: "+1 (767) xxx-xxxx" },
  {
    name: "Dominican Republic",
    code: "+1-809",
    id: "DO",
    format: "+1 (809) xxx-xxxx",
  },
  { name: "East Timor", code: "+670", id: "TL", format: "+670 xxx xxxx" },
  { name: "Ecuador", code: "+593", id: "EC", format: "+593 xx xxx xxxx" },
  { name: "Egypt", code: "+20", id: "EG", format: "+20 xx xxxx xxxx" },
  { name: "El Salvador", code: "+503", id: "SV", format: "+503 xxxx xxxx" },
  {
    name: "Equatorial Guinea",
    code: "+240",
    id: "GQ",
    format: "+240 xx xxx xxxx",
  },
  { name: "Eritrea", code: "+291", id: "ER", format: "+291 x xxx xxx" },
  { name: "Estonia", code: "+372", id: "EE", format: "+372 xxxx xxxx" },
  { name: "Ethiopia", code: "+251", id: "ET", format: "+251 xx xxx xxxx" },
  { name: "Fiji", code: "+679", id: "FJ", format: "+679 xxx xxxx" },
  { name: "Finland", code: "+358", id: "FI", format: "+358 xx xxx xxxx" },
  { name: "France", code: "+33", id: "FR", format: "+33 x xx xx xx xx" },
  { name: "Gabon", code: "+241", id: "GA", format: "+241 x xx xx xx" },
  { name: "Gambia", code: "+220", id: "GM", format: "+220 xxx xxxx" },
  { name: "Georgia", code: "+995", id: "GE", format: "+995 xxx xxxxxx" },
  { name: "Germany", code: "+49", id: "DE", format: "+49 xxx xxxxxxxx" },
  { name: "Ghana", code: "+233", id: "GH", format: "+233 xx xxx xxxx" },
  { name: "Greece", code: "+30", id: "GR", format: "+30 xxx xxx xxxx" },
  { name: "Grenada", code: "+1-473", id: "GD", format: "+1 (473) xxx-xxxx" },
  { name: "Guatemala", code: "+502", id: "GT", format: "+502 xxxx xxxx" },
  { name: "Guinea", code: "+224", id: "GN", format: "+224 xxx xxx xxx" },
  { name: "Guinea-Bissau", code: "+245", id: "GW", format: "+245 xxx xxxx" },
  { name: "Guyana", code: "+592", id: "GY", format: "+592 xxx xxxx" },
  { name: "Haiti", code: "+509", id: "HT", format: "+509 xxxx xxxx" },
  { name: "Honduras", code: "+504", id: "HN", format: "+504 xxxx xxxx" },
  { name: "Hungary", code: "+36", id: "HU", format: "+36 xx xxx xxxx" },
  { name: "Iceland", code: "+354", id: "IS", format: "+354 xxx xxxx" },
  { name: "India", code: "+91", id: "IN", format: "+91 xxxxx xxxxx" },
  { name: "Indonesia", code: "+62", id: "ID", format: "+62 xxx-xxx-xxxx" },
  { name: "Iran", code: "+98", id: "IR", format: "+98 xxx xxx xxxx" },
  { name: "Iraq", code: "+964", id: "IQ", format: "+964 xxx xxx xxxx" },
  { name: "Ireland", code: "+353", id: "IE", format: "+353 xx xxx xxxx" },
  { name: "Israel", code: "+972", id: "IL", format: "+972 xx-xxx-xxxx" },
  { name: "Italy", code: "+39", id: "IT", format: "+39 xxx xxx xxxx" },
  { name: "Ivory Coast", code: "+225", id: "CI", format: "+225 xx xx xx xxxx" },
  { name: "Jamaica", code: "+1-876", id: "JM", format: "+1 (876) xxx-xxxx" },
  { name: "Japan", code: "+81", id: "JP", format: "+81 xx-xxxx-xxxx" },
  { name: "Jordan", code: "+962", id: "JO", format: "+962 x xxxx xxxx" },
  { name: "Kazakhstan", code: "+7", id: "KZ", format: "+7 xxx xxx xxxx" },
  { name: "Kenya", code: "+254", id: "KE", format: "+254 xxx xxxxxx" },
  { name: "Kiribati", code: "+686", id: "KI", format: "+686 xxxx xxxx" },
  { name: "Kosovo", code: "+383", id: "XK", format: "+383 xx xxx xxx" },
  { name: "Kuwait", code: "+965", id: "KW", format: "+965 xxxx xxxx" },
  { name: "Kyrgyzstan", code: "+996", id: "KG", format: "+996 xxx xxxxxx" },
  { name: "Laos", code: "+856", id: "LA", format: "+856 xx xx xxx xxx" },
  { name: "Latvia", code: "+371", id: "LV", format: "+371 xxxx xxxx" },
  { name: "Lebanon", code: "+961", id: "LB", format: "+961 xx xxx xxx" },
  { name: "Lesotho", code: "+266", id: "LS", format: "+266 xxxx xxxx" },
  { name: "Liberia", code: "+231", id: "LR", format: "+231 xx xxx xxxx" },
  { name: "Libya", code: "+218", id: "LY", format: "+218 xx-xxxxxxx" },
  { name: "Liechtenstein", code: "+423", id: "LI", format: "+423 xxx xxxx" },
  { name: "Lithuania", code: "+370", id: "LT", format: "+370 xxx xxxxx" },
  { name: "Luxembourg", code: "+352", id: "LU", format: "+352 xxxx xxxx" },
  { name: "Macedonia", code: "+389", id: "MK", format: "+389 xx xxx xxx" },
  { name: "Madagascar", code: "+261", id: "MG", format: "+261 xx xx xxx xx" },
  { name: "Malawi", code: "+265", id: "MW", format: "+265 x xxxx xxxx" },
  { name: "Malaysia", code: "+60", id: "MY", format: "+60 xx-xxxx xxxx" },
  { name: "Maldives", code: "+960", id: "MV", format: "+960 xxx-xxxx" },
  { name: "Mali", code: "+223", id: "ML", format: "+223 xxxx xxxx" },
  { name: "Malta", code: "+356", id: "MT", format: "+356 xxxx xxxx" },
  { name: "Marshall Islands", code: "+692", id: "MH", format: "+692 xxx xxxx" },
  { name: "Mauritania", code: "+222", id: "MR", format: "+222 xxxx xxxx" },
  { name: "Mauritius", code: "+230", id: "MU", format: "+230 xxxx xxxx" },
  { name: "Mexico", code: "+52", id: "MX", format: "+52 xx xxxx xxxx" },
  { name: "Micronesia", code: "+691", id: "FM", format: "+691 xxx xxxx" },
  { name: "Moldova", code: "+373", id: "MD", format: "+373 xxxx xxxx" },
  { name: "Monaco", code: "+377", id: "MC", format: "+377 xxxx xxxx" },
  { name: "Mongolia", code: "+976", id: "MN", format: "+976 xx xx xxxx" },
  { name: "Montenegro", code: "+382", id: "ME", format: "+382 xx xxx xxx" },
  { name: "Morocco", code: "+212", id: "MA", format: "+212 xx-xxxx-xxx" },
  { name: "Mozambique", code: "+258", id: "MZ", format: "+258 xx xxx xxxx" },
  { name: "Myanmar", code: "+95", id: "MM", format: "+95 x xxx xxxx" },
  { name: "Namibia", code: "+264", id: "NA", format: "+264 xx xxx xxxx" },
  { name: "Nauru", code: "+674", id: "NR", format: "+674 xxx xxxx" },
  { name: "Nepal", code: "+977", id: "NP", format: "+977 xx-xxxx-xxxx" },
  { name: "Netherlands", code: "+31", id: "NL", format: "+31 x xx xx xx xx" },
  { name: "New Zealand", code: "+64", id: "NZ", format: "+64 x-xxx-xxxx" },
  { name: "Nicaragua", code: "+505", id: "NI", format: "+505 xxxx xxxx" },
  { name: "Niger", code: "+227", id: "NE", format: "+227 xx xx xxxx" },
  { name: "Nigeria", code: "+234", id: "NG", format: "+234 xx xxxx xxxx" },
  { name: "North Korea", code: "+850", id: "KP", format: "+850 xx xxx xxxx" },
  { name: "Norway", code: "+47", id: "NO", format: "+47 xxx xx xxx" },
  { name: "Oman", code: "+968", id: "OM", format: "+968 xxxx xxxx" },
  { name: "Pakistan", code: "+92", id: "PK", format: "+92 xxx xxxxxxx" },
  { name: "Palau", code: "+680", id: "PW", format: "+680 xxx xxxx" },
  { name: "Palestine", code: "+970", id: "PS", format: "+970 xx xxx xxxx" },
  { name: "Panama", code: "+507", id: "PA", format: "+507 xxxx-xxxx" },
  { name: "Papua New Guinea", code: "+675", id: "PG", format: "+675 xxx xxxx" },
  { name: "Paraguay", code: "+595", id: "PY", format: "+595 xx xxx xxx" },
  { name: "Peru", code: "+51", id: "PE", format: "+51 xxx xxx xxx" },
  { name: "Philippines", code: "+63", id: "PH", format: "+63 xxx xxx xxxx" },
  { name: "Poland", code: "+48", id: "PL", format: "+48 xx xxx xx xx" },
  { name: "Portugal", code: "+351", id: "PT", format: "+351 xxx xxx xxx" },
  { name: "Qatar", code: "+974", id: "QA", format: "+974 xxxx xxxx" },
  { name: "Romania", code: "+40", id: "RO", format: "+40 xxx xxx xxx" },
  { name: "Russia", code: "+7", id: "RU", format: "+7 xxx xxx xxxx" },
  { name: "Rwanda", code: "+250", id: "RW", format: "+250 xxx xxx xxx" },
  {
    name: "Saint Kitts and Nevis",
    code: "+1-869",
    id: "KN",
    format: "+1 (869) xxx-xxxx",
  },
  {
    name: "Saint Lucia",
    code: "+1-758",
    id: "LC",
    format: "+1 (758) xxx-xxxx",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "+1-784",
    id: "VC",
    format: "+1 (784) xxx-xxxx",
  },
  { name: "Samoa", code: "+685", id: "WS", format: "+685 xxxx xxxx" },
  { name: "San Marino", code: "+378", id: "SM", format: "+378 xxxx xxxx" },
  {
    name: "Sao Tome and Principe",
    code: "+239",
    id: "ST",
    format: "+239 xxxx xxxx",
  },
  { name: "Saudi Arabia", code: "+966", id: "SA", format: "+966 xx xxx xxxx" },
  { name: "Senegal", code: "+221", id: "SN", format: "+221 xx xxx xxxx" },
  { name: "Serbia", code: "+381", id: "RS", format: "+381 xx xxx xxxx" },
  { name: "Seychelles", code: "+248", id: "SC", format: "+248 x xx xx xx" },
  { name: "Sierra Leone", code: "+232", id: "SL", format: "+232 xx xxxxxx" },
  { name: "Singapore", code: "+65", id: "SG", format: "+65 xxxx xxxx" },
  { name: "Slovakia", code: "+421", id: "SK", format: "+421 xxx xxx xxx" },
  { name: "Slovenia", code: "+386", id: "SI", format: "+386 xx xxx xxx" },
  { name: "Solomon Islands", code: "+677", id: "SB", format: "+677 xxxxx" },
  { name: "Somalia", code: "+252", id: "SO", format: "+252 xx xxx xxx" },
  { name: "South Africa", code: "+27", id: "ZA", format: "+27 xx xxx xxxx" },
  { name: "South Korea", code: "+82", id: "KR", format: "+82 xx-xxxx-xxxx" },
  { name: "South Sudan", code: "+211", id: "SS", format: "+211 xx xxx xxxx" },
  { name: "Spain", code: "+34", id: "ES", format: "+34 xxx xxx xxx" },
  { name: "Sri Lanka", code: "+94", id: "LK", format: "+94 xx xxx xxxx" },
  { name: "Sudan", code: "+249", id: "SD", format: "+249 xx xxx xxxx" },
  { name: "Suriname", code: "+597", id: "SR", format: "+597 xxx-xxxx" },
  { name: "Swaziland", code: "+268", id: "SZ", format: "+268 xxxx xxxx" },
  { name: "Sweden", code: "+46", id: "SE", format: "+46 xx xxx xxxx" },
  { name: "Switzerland", code: "+41", id: "CH", format: "+41 xx xxx xxxx" },
  { name: "Syria", code: "+963", id: "SY", format: "+963 xx xxxx xxx" },
  { name: "Taiwan", code: "+886", id: "TW", format: "+886 x xxxx xxxx" },
  { name: "Tajikistan", code: "+992", id: "TJ", format: "+992 xx xxx xxxx" },
  { name: "Tanzania", code: "+255", id: "TZ", format: "+255 xx xxx xxxx" },
  { name: "Thailand", code: "+66", id: "TH", format: "+66 x xxxx xxxx" },
  { name: "Togo", code: "+228", id: "TG", format: "+228 xx xxx xxx" },
  { name: "Tonga", code: "+676", id: "TO", format: "+676 xxxxx" },
  {
    name: "Trinidad and Tobago",
    code: "+1-868",
    id: "TT",
    format: "+1 (868) xxx-xxxx",
  },
  { name: "Tunisia", code: "+216", id: "TN", format: "+216 xx xxx xxx" },
  { name: "Turkey", code: "+90", id: "TR", format: "+90 xxx xxx xxxx" },
  { name: "Turkmenistan", code: "+993", id: "TM", format: "+993 xx xxxxxx" },
  { name: "Tuvalu", code: "+688", id: "TV", format: "+688 xxxxx" },
  { name: "Uganda", code: "+256", id: "UG", format: "+256 xx xxx xxxx" },
  { name: "Ukraine", code: "+380", id: "UA", format: "+380 xx xxx xxxx" },
  {
    name: "United Arab Emirates",
    code: "+971",
    id: "AE",
    format: "+971 xx xxx xxxx",
  },
  { name: "United Kingdom", code: "+44", id: "GB", format: "+44 xxxx xxxxxx" },
  { name: "United States", code: "+1", id: "US", format: "+1 (xxx) xxx-xxxx" },
  { name: "Uruguay", code: "+598", id: "UY", format: "+598 x xxx xxxx" },
  { name: "Uzbekistan", code: "+998", id: "UZ", format: "+998 xx xxx xxxx" },
  { name: "Vanuatu", code: "+678", id: "VU", format: "+678 xxxxx" },
  { name: "Vatican City", code: "+379", id: "VA", format: "+379 xxxx xxxx" },
  { name: "Venezuela", code: "+58", id: "VE", format: "+58 xxx-xxxxxxx" },
  { name: "Vietnam", code: "+84", id: "VN", format: "+84 xx xxxx xxxx" },
  { name: "Yemen", code: "+967", id: "YE", format: "+967 x xxx xxx" },
  { name: "Zambia", code: "+260", id: "ZM", format: "+260 xx xxx xxxx" },
  { name: "Zimbabwe", code: "+263", id: "ZW", format: "+263 xx xxx xxxx" },
];
